
<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 2
        spacing: 10
        Image:
            # source: 'files/photo.png'
            id: img
            size_hint_y: 0.8
        TextInput:
            id: user_query
            size_hint_y: 0.1
        Button:
            text: 'Search Image'
            size_hint_y: 0.1
            on_press: root.get_image_link()

<RootWidget>:
    FirstScreen:
        id: first_screen
        name: 'first_screen'
